# Generated by Django 5.2.1 on 2025-06-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'periode__nomPeriode']},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='periode',
            field=models.ForeignKey(help_text='Période de la réservation (Petit-déjeuner, Déjeuner, DINER)', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='monapp.periode'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('etudiant', 'date', 'periode')},
        ),
    ]
