# Generated by Django 5.2.1 on 2025-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='id',
        ),
        migrations.AddField(
            model_name='paiement',
            name='idPaiement',
            field=models.AutoField(db_column='idPaiement', primary_key=True, serialize=False),
        ),
    ]
