# Generated by Django 5.2.1 on 2025-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text="Genre de l'utilisateur", max_length=2, null=True),
        ),
    ]
