# Generated by Django 5.2.1 on 2025-06-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE etudiant ADD COLUMN IF NOT EXISTS sexe CHAR(1);",
            reverse_sql="ALTER TABLE etudiant DROP COLUMN IF EXISTS sexe;"
        ),
    ]
