# Generated by Django 5.2.1 on 2025-06-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='ticket_quota',
            new_name='ticket_quotas',
        ),
    ]
