# Generated by Django 5.2.1 on 2025-06-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_rename_ticket_quota_etudiant_ticket_quotas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='ticket_quotas',
            new_name='ticket_quota',
        ),
    ]
