# Generated by Django 5.2.1 on 2025-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='nomPeriode',
            field=models.CharField(db_column='nomPeriode', max_length=20),
        ),
    ]
